apiVersion: v2
name: external-secrets
description: External Secrets Operator is a Kubernetes operator wrapper chart
type: application
version: 0.1.0
appVersion: "0.17.0"
dependencies:
  - name: external-secrets
    version: 0.17.0
    repository: https://charts.external-secrets.io
